# Generated by Django 5.1.4 on 2024-12-26 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users_management", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Users_model",
        ),
    ]
